version: '3.7'

services:

  php-swoole:
    container_name: php-swoole
    image: hyperf/hyperf:8.0-alpine-v3.13-swoole
    working_dir: /app
    entrypoint: ["php", "bin/hyperf.php", "server:watch"]
    volumes:
      - ./:/app
    ports:
      - 80:9501
    depends_on:
      - mariadb
      - redis

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
